---
# tasks file for ansible-role-composer
- name: is installed
  stat: path="{{ composer_install_dir }}/composer"
  register: composer_is_installed

- block:

  - name: download installer
    get_url: url=https://getcomposer.org/installer dest=/tmp/composer_installer mode=0755

  - name: install
    shell: php /tmp/composer_installer -- --filename=composer --install-dir={{ composer_install_dir }}
    args:
      chdir: '/tmp'

  - name: is exists composer.phar
    stat: path={{ composer_install_dir }}/composer.phar
    register: composer_is_exists_phar

  - name: rename from composer.phar to composer
    command: "mv {{ composer_install_dir }}/composer.phar {{ composer_install_dir }}/composer"
    when: composer_is_exists_phar.stat.exists

  - name: change permissions
    file:
      path: "{{ composer_install_dir }}/composer"
      owner: root
      group: root
      mode: 0755

  when: composer_is_installed.stat.exists is define and composer_is_installed.stat.exists == true
  become: True
