---
# tasks file for role-composer
- name: is installed
  stat: path="{{ composer_install_dir }}/composer"
  register: composer_is_installed

- block:

  - name: download installer
    get_url: url=https://getcomposer.org/installer dest=/tmp/composer_installer mode=0755

  - name: install
    shell: php /tmp/composer_installer -- --filename=composer --install-dir={{ composer_install_dir }}

  - name: change permissions
    file:
      path: "{{ composer_install_dir }}/composer"
      owner: root
      group: root
      mode: 0755

  when: composer_is_installed.stat.exists is defined and composer_is_installed.stat.exists == false
  become: True
